# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink: /:title/

# Setup
title: CrimeIsDown.com Blog
name: 'CrimeIsDown.com'
description: 'Taking the confusion out of monitoring Chicago crime with data-driven tools.'
url: https://blog.crimeisdown.com
baseurl:
mainsiteurl: https://crimeisdown.com

paginate: 5
paginate_path: page/:num

google-analytics_id: UA-30674963-11
