# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink: /:title/

# Setup
title: CrimeIsDown.com Blog
name: 'CrimeIsDown.com'
description: 'add a description'
url: https://blog.crimeisdown.com
baseurl:
mainsiteurl: https://dev.crimeisdown.com

paginate: 5
paginate_path: page/:num

google-analytics_id: UA-30674963-11
